//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n, A argu) {
      if (n.size() == 1)
         return n.elementAt(0).accept(this,argu);
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         if (n.size() == 1)
            return n.elementAt(0).accept(this,argu);
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      if (n.size() == 1)
         return n.elementAt(0).accept(this,argu);
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * nodeToken -> "MAIN"
    * stmtList -> StmtList()
    * nodeToken1 -> "END"
    * nodeListOptional -> ( Procedure() )*
    * nodeToken2 -> &lt;EOF&gt;
    * </PRE>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.stmtList.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeListOptional -> ( ( Label() )? Stmt() )*
    * </PRE>
    */
   public R visit(StmtList n, A argu) {
      return n.nodeListOptional.accept(this, argu);
   }

   /**
    * <PRE>
    * label -> Label()
    * nodeToken -> "["
    * integerLiteral -> IntegerLiteral()
    * nodeToken1 -> "]"
    * stmtExp -> StmtExp()
    * </PRE>
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      n.label.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.integerLiteral.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.stmtExp.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    * </PRE>
    */
   public R visit(Stmt n, A argu) {
      return n.nodeChoice.accept(this, argu);
   }

   /**
    * <PRE>
    * nodeToken -> "NOOP"
    * </PRE>
    */
   public R visit(NoOpStmt n, A argu) {
      return n.nodeToken.accept(this, argu);
   }

   /**
    * <PRE>
    * nodeToken -> "ERROR"
    * </PRE>
    */
   public R visit(ErrorStmt n, A argu) {
      return n.nodeToken.accept(this, argu);
   }

   /**
    * <PRE>
    * nodeToken -> "CJUMP"
    * exp -> Exp()
    * label -> Label()
    * </PRE>
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.exp.accept(this, argu);
      n.label.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "JUMP"
    * label -> Label()
    * </PRE>
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.label.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "HSTORE"
    * exp -> Exp()
    * integerLiteral -> IntegerLiteral()
    * exp1 -> Exp()
    * </PRE>
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.exp.accept(this, argu);
      n.integerLiteral.accept(this, argu);
      n.exp1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "HLOAD"
    * temp -> Temp()
    * exp -> Exp()
    * integerLiteral -> IntegerLiteral()
    * </PRE>
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.temp.accept(this, argu);
      n.exp.accept(this, argu);
      n.integerLiteral.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "MOVE"
    * temp -> Temp()
    * exp -> Exp()
    * </PRE>
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.temp.accept(this, argu);
      n.exp.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "PRINT"
    * exp -> Exp()
    * </PRE>
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.exp.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> StmtExp()
    *       | Call()
    *       | HAllocate()
    *       | BinOp()
    *       | Temp()
    *       | IntegerLiteral()
    *       | Label()
    * </PRE>
    */
   public R visit(Exp n, A argu) {
      return n.nodeChoice.accept(this, argu);
   }

   /**
    * <PRE>
    * nodeToken -> "BEGIN"
    * stmtList -> StmtList()
    * nodeToken1 -> "RETURN"
    * exp -> Exp()
    * nodeToken2 -> "END"
    * </PRE>
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.stmtList.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.exp.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "CALL"
    * exp -> Exp()
    * nodeToken1 -> "("
    * nodeListOptional -> ( Exp() )*
    * nodeToken2 -> ")"
    * </PRE>
    */
   public R visit(Call n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.exp.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "HALLOCATE"
    * exp -> Exp()
    * </PRE>
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.exp.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * operator -> Operator()
    * exp -> Exp()
    * exp1 -> Exp()
    * </PRE>
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      n.operator.accept(this, argu);
      n.exp.accept(this, argu);
      n.exp1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> "LT"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    * </PRE>
    */
   public R visit(Operator n, A argu) {
      return n.nodeChoice.accept(this, argu);
   }

   /**
    * <PRE>
    * nodeToken -> "TEMP"
    * integerLiteral -> IntegerLiteral()
    * </PRE>
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.integerLiteral.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public R visit(IntegerLiteral n, A argu) {
      return n.nodeToken.accept(this, argu);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public R visit(Label n, A argu) {
      return n.nodeToken.accept(this, argu);
   }

}
