//
// Generated by JTB 1.3.2
//

package syntaxtree;

import visitor.VisitorException;

/**
 * Grammar production:
 * f0 -> Expression()
 * f1 -> ExpressionTail()
 */
public class ExpressionList implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 4719202088609938342L;
public Expression f0;
   public ExpressionTail f1;

   public ExpressionList(Expression n0, ExpressionTail n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(visitor.Visitor v) throws VisitorException {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws VisitorException {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) throws VisitorException {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) throws VisitorException {
      v.visit(this,argu);
   }
}

