//
// Generated by JTB 1.3.2
//

package syntaxtree;

import visitor.VisitorException;

/**
 * Grammar production:
 * f0 -> "!"
 * f1 -> Clause()
 */
public class NotExpression implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 9204180965670945544L;
public NodeToken f0;
   public Clause f1;

   public NotExpression(NodeToken n0, Clause n1) {
      f0 = n0;
      f1 = n1;
   }

   public NotExpression(Clause n0) {
      f0 = new NodeToken("!");
      f1 = n0;
   }

   public void accept(visitor.Visitor v) throws VisitorException {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws VisitorException {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) throws VisitorException {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) throws VisitorException {
      v.visit(this,argu);
   }
}

