//
// Generated by JTB 1.3.2
//

package syntaxtree;

import visitor.VisitorException;

/**
 * Grammar production:
 * f0 -> "this"
 */
public class ThisExpression implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = -1306117886741680235L;
public NodeToken f0;

   public ThisExpression(NodeToken n0) {
      f0 = n0;
   }

   public ThisExpression() {
      f0 = new NodeToken("this");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws VisitorException {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) throws VisitorException {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

