//
// Generated by JTB 1.3.2
//

package syntaxtree;

import visitor.VisitorException;

/**
 * Grammar production:
 * f0 -> ClassDeclaration()
 *       | ClassExtendsDeclaration()
 */
public class TypeDeclaration implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = -590583036415872434L;
public NodeChoice f0;

   public TypeDeclaration(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(visitor.Visitor v) throws VisitorException {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws VisitorException {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) throws VisitorException {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) throws VisitorException {
      v.visit(this,argu);
   }
}

