//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * operator -> Operator()
 * temp -> Temp()
 * simpleExp -> SimpleExp()
 * </PRE>
 */
public class BinOp implements Node {
   private Node parent;
   public Operator operator;
   public Temp temp;
   public SimpleExp simpleExp;

   public BinOp(Operator n0, Temp n1, SimpleExp n2) {
      operator = n0;
      if ( operator != null ) operator.setParent(this);
      temp = n1;
      if ( temp != null ) temp.setParent(this);
      simpleExp = n2;
      if ( simpleExp != null ) simpleExp.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

