//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "HALLOCATE"
 * simpleExp -> SimpleExp()
 * </PRE>
 */
public class HAllocate implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public SimpleExp simpleExp;

   public HAllocate(NodeToken n0, SimpleExp n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      simpleExp = n1;
      if ( simpleExp != null ) simpleExp.setParent(this);
   }

   public HAllocate(SimpleExp n0) {
      nodeToken = new NodeToken("HALLOCATE");
      if ( nodeToken != null ) nodeToken.setParent(this);
      simpleExp = n0;
      if ( simpleExp != null ) simpleExp.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

