//
// Generated by JTB 1.3.2
//

package syntaxtree;

import visitor.VisitorException;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(visitor.Visitor v) throws VisitorException;
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws VisitorException;
   public <R> R accept(visitor.GJNoArguVisitor<R> v) throws VisitorException;
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) throws VisitorException;
}

