//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "ALOAD"
 * reg -> Reg()
 * spilledArg -> SpilledArg()
 * </PRE>
 */
public class ALoadStmt implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public Reg reg;
   public SpilledArg spilledArg;

   public ALoadStmt(NodeToken n0, Reg n1, SpilledArg n2) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      reg = n1;
      if ( reg != null ) reg.setParent(this);
      spilledArg = n2;
      if ( spilledArg != null ) spilledArg.setParent(this);
   }

   public ALoadStmt(Reg n0, SpilledArg n1) {
      nodeToken = new NodeToken("ALOAD");
      if ( nodeToken != null ) nodeToken.setParent(this);
      reg = n0;
      if ( reg != null ) reg.setParent(this);
      spilledArg = n1;
      if ( spilledArg != null ) spilledArg.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

