//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "MAIN"
 * nodeToken1 -> "["
 * integerLiteral -> IntegerLiteral()
 * nodeToken2 -> "]"
 * nodeToken3 -> "["
 * integerLiteral1 -> IntegerLiteral()
 * nodeToken4 -> "]"
 * nodeToken5 -> "["
 * integerLiteral2 -> IntegerLiteral()
 * nodeToken6 -> "]"
 * stmtList -> StmtList()
 * nodeToken7 -> "END"
 * nodeListOptional -> ( Procedure() )*
 * nodeToken8 -> &lt;EOF&gt;
 * </PRE>
 */
public class Goal implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public NodeToken nodeToken1;
   public IntegerLiteral integerLiteral;
   public NodeToken nodeToken2;
   public NodeToken nodeToken3;
   public IntegerLiteral integerLiteral1;
   public NodeToken nodeToken4;
   public NodeToken nodeToken5;
   public IntegerLiteral integerLiteral2;
   public NodeToken nodeToken6;
   public StmtList stmtList;
   public NodeToken nodeToken7;
   public NodeListOptional nodeListOptional;
   public NodeToken nodeToken8;

   public Goal(NodeToken n0, NodeToken n1, IntegerLiteral n2, NodeToken n3, NodeToken n4, IntegerLiteral n5, NodeToken n6, NodeToken n7, IntegerLiteral n8, NodeToken n9, StmtList n10, NodeToken n11, NodeListOptional n12, NodeToken n13) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = n1;
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      integerLiteral = n2;
      if ( integerLiteral != null ) integerLiteral.setParent(this);
      nodeToken2 = n3;
      if ( nodeToken2 != null ) nodeToken2.setParent(this);
      nodeToken3 = n4;
      if ( nodeToken3 != null ) nodeToken3.setParent(this);
      integerLiteral1 = n5;
      if ( integerLiteral1 != null ) integerLiteral1.setParent(this);
      nodeToken4 = n6;
      if ( nodeToken4 != null ) nodeToken4.setParent(this);
      nodeToken5 = n7;
      if ( nodeToken5 != null ) nodeToken5.setParent(this);
      integerLiteral2 = n8;
      if ( integerLiteral2 != null ) integerLiteral2.setParent(this);
      nodeToken6 = n9;
      if ( nodeToken6 != null ) nodeToken6.setParent(this);
      stmtList = n10;
      if ( stmtList != null ) stmtList.setParent(this);
      nodeToken7 = n11;
      if ( nodeToken7 != null ) nodeToken7.setParent(this);
      nodeListOptional = n12;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      nodeToken8 = n13;
      if ( nodeToken8 != null ) nodeToken8.setParent(this);
   }

   public Goal(IntegerLiteral n0, IntegerLiteral n1, IntegerLiteral n2, StmtList n3, NodeListOptional n4) {
      nodeToken = new NodeToken("MAIN");
      if ( nodeToken != null ) nodeToken.setParent(this);
      nodeToken1 = new NodeToken("[");
      if ( nodeToken1 != null ) nodeToken1.setParent(this);
      integerLiteral = n0;
      if ( integerLiteral != null ) integerLiteral.setParent(this);
      nodeToken2 = new NodeToken("]");
      if ( nodeToken2 != null ) nodeToken2.setParent(this);
      nodeToken3 = new NodeToken("[");
      if ( nodeToken3 != null ) nodeToken3.setParent(this);
      integerLiteral1 = n1;
      if ( integerLiteral1 != null ) integerLiteral1.setParent(this);
      nodeToken4 = new NodeToken("]");
      if ( nodeToken4 != null ) nodeToken4.setParent(this);
      nodeToken5 = new NodeToken("[");
      if ( nodeToken5 != null ) nodeToken5.setParent(this);
      integerLiteral2 = n2;
      if ( integerLiteral2 != null ) integerLiteral2.setParent(this);
      nodeToken6 = new NodeToken("]");
      if ( nodeToken6 != null ) nodeToken6.setParent(this);
      stmtList = n3;
      if ( stmtList != null ) stmtList.setParent(this);
      nodeToken7 = new NodeToken("END");
      if ( nodeToken7 != null ) nodeToken7.setParent(this);
      nodeListOptional = n4;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
      nodeToken8 = new NodeToken("");
      if ( nodeToken8 != null ) nodeToken8.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

