//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "PASSARG"
 * integerLiteral -> IntegerLiteral()
 * reg -> Reg()
 * </PRE>
 */
public class PassArgStmt implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public IntegerLiteral integerLiteral;
   public Reg reg;

   public PassArgStmt(NodeToken n0, IntegerLiteral n1, Reg n2) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      integerLiteral = n1;
      if ( integerLiteral != null ) integerLiteral.setParent(this);
      reg = n2;
      if ( reg != null ) reg.setParent(this);
   }

   public PassArgStmt(IntegerLiteral n0, Reg n1) {
      nodeToken = new NodeToken("PASSARG");
      if ( nodeToken != null ) nodeToken.setParent(this);
      integerLiteral = n0;
      if ( integerLiteral != null ) integerLiteral.setParent(this);
      reg = n1;
      if ( reg != null ) reg.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

