//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

   //
   // GJ void Auto class visitors
   //

   public void visit(NodeList n, A argu);
   public void visit(NodeListOptional n, A argu);
   public void visit(NodeOptional n, A argu);
   public void visit(NodeSequence n, A argu);
   public void visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * nodeToken -> "MAIN"
    * nodeToken1 -> "["
    * integerLiteral -> IntegerLiteral()
    * nodeToken2 -> "]"
    * nodeToken3 -> "["
    * integerLiteral1 -> IntegerLiteral()
    * nodeToken4 -> "]"
    * nodeToken5 -> "["
    * integerLiteral2 -> IntegerLiteral()
    * nodeToken6 -> "]"
    * stmtList -> StmtList()
    * nodeToken7 -> "END"
    * nodeListOptional -> ( Procedure() )*
    * nodeToken8 -> &lt;EOF&gt;
    * </PRE>
    */
   public void visit(Goal n, A argu);

   /**
    * <PRE>
    * nodeListOptional -> ( ( Label() )? Stmt() )*
    * </PRE>
    */
   public void visit(StmtList n, A argu);

   /**
    * <PRE>
    * label -> Label()
    * nodeToken -> "["
    * integerLiteral -> IntegerLiteral()
    * nodeToken1 -> "]"
    * nodeToken2 -> "["
    * integerLiteral1 -> IntegerLiteral()
    * nodeToken3 -> "]"
    * nodeToken4 -> "["
    * integerLiteral2 -> IntegerLiteral()
    * nodeToken5 -> "]"
    * stmtList -> StmtList()
    * nodeToken6 -> "END"
    * </PRE>
    */
   public void visit(Procedure n, A argu);

   /**
    * <PRE>
    * nodeChoice -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    * </PRE>
    */
   public void visit(Stmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "NOOP"
    * </PRE>
    */
   public void visit(NoOpStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "ERROR"
    * </PRE>
    */
   public void visit(ErrorStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "CJUMP"
    * reg -> Reg()
    * label -> Label()
    * </PRE>
    */
   public void visit(CJumpStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "JUMP"
    * label -> Label()
    * </PRE>
    */
   public void visit(JumpStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "HSTORE"
    * reg -> Reg()
    * integerLiteral -> IntegerLiteral()
    * reg1 -> Reg()
    * </PRE>
    */
   public void visit(HStoreStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "HLOAD"
    * reg -> Reg()
    * reg1 -> Reg()
    * integerLiteral -> IntegerLiteral()
    * </PRE>
    */
   public void visit(HLoadStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "MOVE"
    * reg -> Reg()
    * exp -> Exp()
    * </PRE>
    */
   public void visit(MoveStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "PRINT"
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public void visit(PrintStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "ALOAD"
    * reg -> Reg()
    * spilledArg -> SpilledArg()
    * </PRE>
    */
   public void visit(ALoadStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "ASTORE"
    * spilledArg -> SpilledArg()
    * reg -> Reg()
    * </PRE>
    */
   public void visit(AStoreStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "PASSARG"
    * integerLiteral -> IntegerLiteral()
    * reg -> Reg()
    * </PRE>
    */
   public void visit(PassArgStmt n, A argu);

   /**
    * <PRE>
    * nodeToken -> "CALL"
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public void visit(CallStmt n, A argu);

   /**
    * <PRE>
    * nodeChoice -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    * </PRE>
    */
   public void visit(Exp n, A argu);

   /**
    * <PRE>
    * nodeToken -> "HALLOCATE"
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public void visit(HAllocate n, A argu);

   /**
    * <PRE>
    * operator -> Operator()
    * reg -> Reg()
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public void visit(BinOp n, A argu);

   /**
    * <PRE>
    * nodeChoice -> "LT"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    * </PRE>
    */
   public void visit(Operator n, A argu);

   /**
    * <PRE>
    * nodeToken -> "SPILLEDARG"
    * integerLiteral -> IntegerLiteral()
    * </PRE>
    */
   public void visit(SpilledArg n, A argu);

   /**
    * <PRE>
    * nodeChoice -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    * </PRE>
    */
   public void visit(SimpleExp n, A argu);

   /**
    * <PRE>
    * nodeChoice -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    * </PRE>
    */
   public void visit(Reg n, A argu);

   /**
    * <PRE>
    * nodeToken -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public void visit(IntegerLiteral n, A argu);

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(Label n, A argu);

}

