//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n) {
      if (n.size() == 1)
         return n.elementAt(0).accept(this);
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         if (n.size() == 1)
            return n.elementAt(0).accept(this);
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      if (n.size() == 1)
         return n.elementAt(0).accept(this);
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * nodeToken -> "MAIN"
    * stmtList -> StmtList()
    * nodeToken1 -> "END"
    * nodeListOptional -> ( Procedure() )*
    * nodeToken2 -> &lt;EOF&gt;
    * </PRE>
    */
   public R visit(Goal n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.stmtList.accept(this);
      n.nodeToken1.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken2.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeListOptional -> ( ( Label() )? Stmt() )*
    * </PRE>
    */
   public R visit(StmtList n) {
      return n.nodeListOptional.accept(this);
   }

   /**
    * <PRE>
    * label -> Label()
    * nodeToken -> "["
    * integerLiteral -> IntegerLiteral()
    * nodeToken1 -> "]"
    * stmtExp -> StmtExp()
    * </PRE>
    */
   public R visit(Procedure n) {
      R _ret=null;
      n.label.accept(this);
      n.nodeToken.accept(this);
      n.integerLiteral.accept(this);
      n.nodeToken1.accept(this);
      n.stmtExp.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    * </PRE>
    */
   public R visit(Stmt n) {
      return n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "NOOP"
    * </PRE>
    */
   public R visit(NoOpStmt n) {
      return n.nodeToken.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "ERROR"
    * </PRE>
    */
   public R visit(ErrorStmt n) {
      return n.nodeToken.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "CJUMP"
    * temp -> Temp()
    * label -> Label()
    * </PRE>
    */
   public R visit(CJumpStmt n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.temp.accept(this);
      n.label.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "JUMP"
    * label -> Label()
    * </PRE>
    */
   public R visit(JumpStmt n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.label.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "HSTORE"
    * temp -> Temp()
    * integerLiteral -> IntegerLiteral()
    * temp1 -> Temp()
    * </PRE>
    */
   public R visit(HStoreStmt n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.temp.accept(this);
      n.integerLiteral.accept(this);
      n.temp1.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "HLOAD"
    * temp -> Temp()
    * temp1 -> Temp()
    * integerLiteral -> IntegerLiteral()
    * </PRE>
    */
   public R visit(HLoadStmt n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.temp.accept(this);
      n.temp1.accept(this);
      n.integerLiteral.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "MOVE"
    * temp -> Temp()
    * exp -> Exp()
    * </PRE>
    */
   public R visit(MoveStmt n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.temp.accept(this);
      n.exp.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "PRINT"
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public R visit(PrintStmt n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.simpleExp.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    * </PRE>
    */
   public R visit(Exp n) {
      return n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "BEGIN"
    * stmtList -> StmtList()
    * nodeToken1 -> "RETURN"
    * simpleExp -> SimpleExp()
    * nodeToken2 -> "END"
    * </PRE>
    */
   public R visit(StmtExp n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.stmtList.accept(this);
      n.nodeToken1.accept(this);
      n.simpleExp.accept(this);
      n.nodeToken2.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "CALL"
    * simpleExp -> SimpleExp()
    * nodeToken1 -> "("
    * nodeListOptional -> ( Temp() )*
    * nodeToken2 -> ")"
    * </PRE>
    */
   public R visit(Call n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.simpleExp.accept(this);
      n.nodeToken1.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken2.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "HALLOCATE"
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public R visit(HAllocate n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.simpleExp.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * operator -> Operator()
    * temp -> Temp()
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public R visit(BinOp n) {
      R _ret=null;
      n.operator.accept(this);
      n.temp.accept(this);
      n.simpleExp.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> "LT"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    * </PRE>
    */
   public R visit(Operator n) {
      return n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeChoice -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    * </PRE>
    */
   public R visit(SimpleExp n) {
      return n.nodeChoice.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> "TEMP"
    * integerLiteral -> IntegerLiteral()
    * </PRE>
    */
   public R visit(Temp n) {
      R _ret=null;
      n.nodeToken.accept(this);
      n.integerLiteral.accept(this);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public R visit(IntegerLiteral n) {
      return n.nodeToken.accept(this);
   }

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public R visit(Label n) {
      return n.nodeToken.accept(this);
   }

}
