//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * nodeToken -> "MAIN"
    * stmtList -> StmtList()
    * nodeToken1 -> "END"
    * nodeListOptional -> ( Procedure() )*
    * nodeToken2 -> &lt;EOF&gt;
    * </PRE>
    */
   public void visit(Goal n);

   /**
    * <PRE>
    * nodeListOptional -> ( ( Label() )? Stmt() )*
    * </PRE>
    */
   public void visit(StmtList n);

   /**
    * <PRE>
    * label -> Label()
    * nodeToken -> "["
    * integerLiteral -> IntegerLiteral()
    * nodeToken1 -> "]"
    * stmtExp -> StmtExp()
    * </PRE>
    */
   public void visit(Procedure n);

   /**
    * <PRE>
    * nodeChoice -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    * </PRE>
    */
   public void visit(Stmt n);

   /**
    * <PRE>
    * nodeToken -> "NOOP"
    * </PRE>
    */
   public void visit(NoOpStmt n);

   /**
    * <PRE>
    * nodeToken -> "ERROR"
    * </PRE>
    */
   public void visit(ErrorStmt n);

   /**
    * <PRE>
    * nodeToken -> "CJUMP"
    * temp -> Temp()
    * label -> Label()
    * </PRE>
    */
   public void visit(CJumpStmt n);

   /**
    * <PRE>
    * nodeToken -> "JUMP"
    * label -> Label()
    * </PRE>
    */
   public void visit(JumpStmt n);

   /**
    * <PRE>
    * nodeToken -> "HSTORE"
    * temp -> Temp()
    * integerLiteral -> IntegerLiteral()
    * temp1 -> Temp()
    * </PRE>
    */
   public void visit(HStoreStmt n);

   /**
    * <PRE>
    * nodeToken -> "HLOAD"
    * temp -> Temp()
    * temp1 -> Temp()
    * integerLiteral -> IntegerLiteral()
    * </PRE>
    */
   public void visit(HLoadStmt n);

   /**
    * <PRE>
    * nodeToken -> "MOVE"
    * temp -> Temp()
    * exp -> Exp()
    * </PRE>
    */
   public void visit(MoveStmt n);

   /**
    * <PRE>
    * nodeToken -> "PRINT"
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public void visit(PrintStmt n);

   /**
    * <PRE>
    * nodeChoice -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    * </PRE>
    */
   public void visit(Exp n);

   /**
    * <PRE>
    * nodeToken -> "BEGIN"
    * stmtList -> StmtList()
    * nodeToken1 -> "RETURN"
    * simpleExp -> SimpleExp()
    * nodeToken2 -> "END"
    * </PRE>
    */
   public void visit(StmtExp n);

   /**
    * <PRE>
    * nodeToken -> "CALL"
    * simpleExp -> SimpleExp()
    * nodeToken1 -> "("
    * nodeListOptional -> ( Temp() )*
    * nodeToken2 -> ")"
    * </PRE>
    */
   public void visit(Call n);

   /**
    * <PRE>
    * nodeToken -> "HALLOCATE"
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public void visit(HAllocate n);

   /**
    * <PRE>
    * operator -> Operator()
    * temp -> Temp()
    * simpleExp -> SimpleExp()
    * </PRE>
    */
   public void visit(BinOp n);

   /**
    * <PRE>
    * nodeChoice -> "LT"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    * </PRE>
    */
   public void visit(Operator n);

   /**
    * <PRE>
    * nodeChoice -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    * </PRE>
    */
   public void visit(SimpleExp n);

   /**
    * <PRE>
    * nodeToken -> "TEMP"
    * integerLiteral -> IntegerLiteral()
    * </PRE>
    */
   public void visit(Temp n);

   /**
    * <PRE>
    * nodeToken -> &lt;INTEGER_LITERAL&gt;
    * </PRE>
    */
   public void visit(IntegerLiteral n);

   /**
    * <PRE>
    * nodeToken -> &lt;IDENTIFIER&gt;
    * </PRE>
    */
   public void visit(Label n);

}

