//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

import visitor.VisitorException;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "CJUMP"
 * exp -> Exp()
 * label -> Label()
 * </PRE>
 */
public class CJumpStmt implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = -2521524492436756459L;
private Node parent;
   public NodeToken nodeToken;
   public Exp exp;
   public Label label;

   public CJumpStmt(NodeToken n0, Exp n1, Label n2) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      exp = n1;
      if ( exp != null ) exp.setParent(this);
      label = n2;
      if ( label != null ) label.setParent(this);
   }

   public CJumpStmt(Exp n0, Label n1) {
      nodeToken = new NodeToken("CJUMP");
      if ( nodeToken != null ) nodeToken.setParent(this);
      exp = n0;
      if ( exp != null ) exp.setParent(this);
      label = n1;
      if ( label != null ) label.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws VisitorException {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

