//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "HALLOCATE"
 * exp -> Exp()
 * </PRE>
 */
public class HAllocate implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public Exp exp;

   public HAllocate(NodeToken n0, Exp n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      exp = n1;
      if ( exp != null ) exp.setParent(this);
   }

   public HAllocate(Exp n0) {
      nodeToken = new NodeToken("HALLOCATE");
      if ( nodeToken != null ) nodeToken.setParent(this);
      exp = n0;
      if ( exp != null ) exp.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

