//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

import visitor.VisitorException;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "JUMP"
 * label -> Label()
 * </PRE>
 */
public class JumpStmt implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = -3900126809120883393L;
private Node parent;
   public NodeToken nodeToken;
   public Label label;

   public JumpStmt(NodeToken n0, Label n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      label = n1;
      if ( label != null ) label.setParent(this);
   }

   public JumpStmt(Label n0) {
      nodeToken = new NodeToken("JUMP");
      if ( nodeToken != null ) nodeToken.setParent(this);
      label = n0;
      if ( label != null ) label.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws VisitorException {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

