//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "NOOP"
 * </PRE>
 */
public class NoOpStmt implements Node {
   private Node parent;
   public NodeToken nodeToken;

   public NoOpStmt(NodeToken n0) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
   }

   public NoOpStmt() {
      nodeToken = new NodeToken("NOOP");
      if ( nodeToken != null ) nodeToken.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

