//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

import visitor.VisitorException;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "PRINT"
 * exp -> Exp()
 * </PRE>
 */
public class PrintStmt implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = -2262407357979874799L;
private Node parent;
   public NodeToken nodeToken;
   public Exp exp;

   public PrintStmt(NodeToken n0, Exp n1) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      exp = n1;
      if ( exp != null ) exp.setParent(this);
   }

   public PrintStmt(Exp n0) {
      nodeToken = new NodeToken("PRINT");
      if ( nodeToken != null ) nodeToken.setParent(this);
      exp = n0;
      if ( exp != null ) exp.setParent(this);
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) throws VisitorException {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

